name: Simple Github Actions
on: [push]
jobs:
  simple-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Inspect variables supplied by GitHub
        run: |
          echo "Triggering commit : ${GITHUB_SHA}"
          echo "Repository        : ${GITHUB_REPOSITORY}"
          echo "Actions Directory : ${GITHUB_WORKSPACE}"
          echo "Token             : ${{ github.token }}"
      - name: List files before checkout
        run: |
          pwd
          ls -a
      - name: Checkout
        uses: actions/checkout@v3
      - name: List files after checkout
        run: |
          pwd
          ls -a
      - name: Greet someone
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Happy World
      - name: Log time
        run: echo "${{ steps.greet.outputs.time }}"
