name: Context testing
on: 
  push:
    branches:
      - feature/**
  # - pull_request

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: eccho '${{ toJSON(github) }}'
      - name: Dump job context
        if: failure()
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        if: always()
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
  functions_demo:
    runs-on: ubuntu-latest
    steps:
      - name: Dump functions
        run: |
          echo ${{ contains('hello', 'll') }}
          echo ${{ startsWith( 'hello', 'he' ) }}
          echo ${{ endsWith( 'hello', 'lo') }}
          echo ${{ format('Hello {0} {1} {2}', 'Happy', 'World', '!') }}
