name: Docker Container
on: push
jobs:
  container-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      - name: Log node version
        run: node -v
      - name: HW from docker
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: /bin/echo
          args: Hello World
      - name: Log node version inside docker
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: /usr/local/bin/node
          args: -v
      - name: Call script
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: ./script.sh
