name: Matrix
on:
  - push
jobs:
  set-up-node:
    runs-on: ubuntu-latest
    steps:
      - name: Log node version
        run: node -v
      - name: Change node version
        uses: actions/setup-node@v3
        with:
          node-version: 6
      - name: Log node version after update
        run: node -v