name: Shell Commands
on:
  # push:
  # schedule:
    # - cron: "0/5 * * * *"
    # - cron: "0/6 * * * *"
  repository_dispatch:
    types:
      - build
jobs:
  simple-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Echo production payload
        run : echo "Environment from client => ${{ github.event.client_payload.env }}"
      - name: Echo a string
        run: echo "Hello Happy World!"
      - name: Check versions using multi-line command
        run: |
          node -v
          npm -v
      - name: Python command
        run: |
          import platform
          print(platform.processor())
        shell: python
  window-commands:
    runs-on: windows-latest
    needs: [
      "simple-shell-commands"
    ]
    steps:
      - name: Get directory through powershell
        run: Get-Location
      - name: Get directory through bash
        run: pwd
        shell: bash
