name: Shell Commands
on: [push]
jobs:
  simple-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: echo "Hello Happy World!"
      - name: Check versions using multi-line command
        run: |
          node -v
          npm -v
      - name: Python command
        run: |
          import platform
          print(platform.processor())
        shell: python
