name: Shell Commands
on: [push]
jobs:
  simple-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: eccho "Hello Happy World!"
      - name: Check versions using multi-line command
        run: |
          node -v
          npm -v
        
    
